### ISSUE TITLE
About the "Lead-wise Grad-CAM" technique 

### ISSUE THREAD

**Issue by Fabeye** [lhkhiem28/LightX3ECG#3]
I am trying to visualize attention results using Grad-CAM, as you did in your paper. Can you provide code snippet that you used for this purpose or give more detailed explanation?

**Comment by lhkhiem28** [comment]
@Fabeye I'm cleaning up and retesting the code. I will upload the code and an example within the next week

**Comment by decoder-99** [comment]
@lhkhiem28 I am interested in this part of your code too. Can you show an example?

**Comment by lhkhiem28** [comment]
Hi. I apologize for the late response. For future development, we decided to not release this part of the code at the moment. Sorry for the inconvenience. 
You can follow this tutorial and try it by yourself: https://captum.ai/api/layer.html#gradcam
Thanks.
