### ISSUE TITLE
Explainability and results

### ISSUE THREAD

**Issue by isma40000** [lhkhiem28/LightX3ECG#4]
Hello, my companions and I would like to use your LightX3ECG project to classify diseases. We are trying to understand the code better, is there any kind of manual or guide of the code?, apart from the paper. Do you have any recomendation to get better predictions? Is there any code to get the results from table 2 (from the paper)?
Thank you.

**Comment by lhkhiem28** [comment]
Hi. We do not have a guide to the code at the moment. 
You can visit the 2nd part of our project as a recommendation for improvement. 
https://github.com/lhkhiem28/X3ECGpp
Thanks.

**Comment by isma40000** [comment]
Thank you, we will take a look to the second part 👌
