### ISSUE TITLE
Chapman's execution

### ISSUE THREAD

**Issue by isma40000** [lhkhiem28/LightX3ECG#5]
Hello, my partners and I are trying to execute the Chapman training but we are no capable of doing so. We could execute the CPSC part without issues. 
* How must be the Chapman one executed?
* Have the Chapman cases had the baseline removed?
* What are the units of the Chapman ECGs mV, V?

Thank you in advance. Any extra information would be appreciated.

**Comment by lhkhiem28** [comment]
Hi. 
- The code was configured for training Chapman by default (by turning off the argument --multilabel, turn it on for training CPSC)
- We used the raw the Chapman dataset
- The amplitude unit is a microvolt
More information about this dataset can be found here:
https://www.nature.com/articles/s41597-020-0386-x

**Comment by isma40000** [comment]
Thank you very much. Keep up the good work. 😉
